clear
addpath /tank/chaocean/MITgcm/utils/matlab;
addpath /tank/chaocean/scripts
depth=rd_chao12('/tank/chaocean/grid_chaO/gridMIT_update1/Depth');
file='/tank/chaocean/bill/RUNS/ORAR/ensmean/umjan1967';
um=rd_chao12(file);
file='/tank/chaocean/bill/RUNS/ORAR/ensmean/vmjan1967';
vm=rd_chao12(file);
speed=um(:,:,1).^2+vm(:,:,1).^2;speed=sqrt(speed);
longitude=360-98+(0:1300)/12;
%longitude=longitude-360;
latitude=-20+(0:899)/12;
xc=211:400;yc=580:760;
figure(1);
clf;
cs=contour(longitude(xc),latitude(yc),speed(xc,yc,1)',[0:.05:2]);colorbar;
colormap('jet');
hold on;
cs=contour(longitude(xc),latitude(yc),depth(xc,yc)',[-.01 .01],'k','linewidth',2);
set(gca,'xtick',10:5:360,'fontsize',12);
set(gca,'xticklabel',-([10:5:360]-360));
set(gca,'ytick',10:5:55,'fontsize',12);
xlabel('Longitude (W)','fontsize',14);
ylabel('Latitude (N)','fontsize',14);
title('Surface Speed (m/s)','fontsize',16);
xfirst=300;xlast=xfirst+47;
yfirst=649;ylast=yfirst+47;
lf=longitude(xfirst);ll=longitude(xlast);
laf=latitude(yfirst);lal=latitude(ylast);
plot([lf lf],[laf lal],'k','linewidth',2);
plot([ll ll],[laf lal],'k','linewidth',2);
plot([lf ll],[laf laf],'k','linewidth',2);
plot([lf ll],[lal lal],'k','linewidth',2);
hold off;
savefig('/tank/chaocean/bill/RUNS/ORAR/ensmean/surfspeed.fig');
saveas(gcf,'/tank/chaocean/bill/RUNS/ORAR/ensmean/surfspeed.pdf');
figure(2);
subplot(2,2,1);
xc=xfirst:xlast;yc=yfirst:ylast;
cs=contour(longitude(xc),latitude(yc),um(xc,yc,9)',[0:.05:2]);colorbar;
colormap('jet');
hold on;
set(gca,'xtick',10:2:360,'fontsize',12);
set(gca,'xticklabel',-([10:2:360]-360));
set(gca,'ytick',10:2:55,'fontsize',12);
ylabel('Latitude (N)','fontsize',14);
title('U mean (94m)','fontsize',14);
subplot(2,2,2);
cs=contour(longitude(xc),latitude(yc),vm(xc,yc,9)',[0:.02:2]);colorbar;
colormap('jet');
hold on;
set(gca,'xtick',10:2:360,'fontsize',12);
set(gca,'xticklabel',-([10:2:360]-360));
set(gca,'ytick',10:2:55,'fontsize',12);
title('V mean (94m)','fontsize',14);
subplot(2,2,3);
cs=contour(longitude(xc),latitude(yc),um(xc,yc,21)',[0:.02:2]);colorbar;
colormap('jet');
hold on;
set(gca,'xtick',10:2:360,'fontsize',12);
set(gca,'xticklabel',-([10:2:360]-360));
set(gca,'ytick',10:2:55,'fontsize',12);
xlabel('Longitude (W)','fontsize',14);
ylabel('Latitudei (N)','fontsize',14);
title('U mean (628m)','fontsize',14);
subplot(2,2,4);
cs=contour(longitude(xc),latitude(yc),vm(xc,yc,21)',[0:.01:2]);colorbar;
colormap('jet');
hold on;
set(gca,'xtick',10:2:360,'fontsize',12);
set(gca,'xticklabel',-([10:2:360]-360));
set(gca,'ytick',10:2:55,'fontsize',12);
xlabel('Longitude (W)','fontsize',14);
title('V mean (628m)','fontsize',14);
savefig('/tank/chaocean/bill/RUNS/ORAR/ensmean/meanfields.fig');
saveas(gcf,'/tank/chaocean/bill/RUNS/ORAR/ensmean/meanfields.pdf');
